const AUTO_JOIN_KEY = "voice:auto_join"

const voiceState = {
  selfId: "",
  isVoiceChannel: false,
  serverId: null,
  channelName: "",
  contextKey: "",
  canSpeak: true,
  isReady: false,
  isConnected: false,
  isJoined: false,
  joinedAtTs: 0,
  serverClockOffsetMs: 0,
  isConnecting: false,
  isMuted: false,
  autoJoinEnabled: false,
  manualLeave: false,
  iceFailureNotified: false,
  outputDeviceFailureNotified: false,
  audioContext: null,
  analyserLoopId: 0,
  presenceTimerId: 0,
  lastPresenceKey: "",
  presenceIds: new Set(),
  presenceInitialized: false,
  channelPresenceByKey: new Map(),
  analysers: new Map(),
  speakingState: new Map(),
  tileEls: new Map(),
  rawStream: null,
  localStream: null,
  inputGainNode: null,
  inputSourceNode: null,
  inputDeviceId: "",
  outputDeviceId: "",
  outputVolume: 0.8,
  inputGain: 1,
  pushToTalkEnabled: false,
  pushToTalkKey: "KeyV",
  pushToTalkActive: false,
  wasMutedBeforePtt: false,
  isCapturingPttKey: false,
  peers: new Map(),
  peerMeta: new Map(),
  peerStats: new Map(),
  qualityTimerId: 0,
  qualitySummary: {
    level: "Unknown",
    rttMs: 0,
    jitterMs: 0,
    lossPct: 0,
    updatedAt: 0
  },
  audioEls: new Map(),
  participants: new Map()
}

export { AUTO_JOIN_KEY, voiceState }
